version: "3.9"
name: book-store
services:
  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.1
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 30s
      retries: 5